ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjA5ZmJiOWQ4LTNjMGQtNGI3Ny04ZmE2LTRkODMyNGJmYmQzMSIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc2MDQ1MzY1MiwiaWF0IjoxNzYwMzY3MjUyLCJqdGkiOiJQU3I2T3hsRFpOY0RUdGlxcFhNREVaY1lCVE1hd2VRbXV2VzAifQ.voOivHugLNe6wDty_sHb5aAgGtKOKpHK0TxhhVHCUjc489RPwmVvAQ042HcjdutAP0_B7Pbz09OVB-x6OUvTaA
ACNT_PRDT_CD: '01'
APP_KEY: PSr6OxlDZNcDTtiqpXMDEZcYBTMaweQmuvW0
APP_SECRET: G5porksw1kxyxMX47qyPrpK8LOj100FU7ORFoyB6EqU7m23OLgYZFPlgULIbWXpIKOz2pJRBxk0QXS3FbGqe+dAGofVX91lChtngEw2d0TmRJ0qCRHIlg/hY9N9s4nBkXqmOju2G0p6/NILDcssdWUY6c0JCNAN8ER1xLucroE/RvAj8oW0=
CANO: '43154696'
DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1399740614429638687/tFRbLzV0WPJT3xDBqaK9uQqrGWhctpbXX9gyDw6CLAX7QXK16Q-3TaF4z9zyG7vNUnjc
TOKEN_ISSUED_AT: '2025-10-14 03:00:05'
URL_BASE: https://openapi.koreainvestment.com:9443
